### ISSUE TITLE
Update symfony YAML parser to 3.3.18 for PHP 7.4+ compatibility?

### ISSUE THREAD

**Issue by nomakewan** [railsphp/railsphp#12]
Hello,

I'm using railsphp on a web server that recently updated its PHP subsystem to 7.4. Luckily most of the server is still functioning, but some background tasks are failing due to the error "Array and string offset access syntax with curly braces is deprecated". It appears that this is an issue with the symfony YAML parser's 2.x branch, and has been corrected in the 3.3 branch according to https://github.com/modmore/Gitify/issues/381

Would it be possible to update railsphp to support symfony YAML 3.3.18?

Thank you very much.

**Comment by Parziphal** [comment]
Hello there, I will look into this soon, or you can generate a PR if you got the fix.

**Comment by nomakewan** [comment]
Hello, thank you so much for the response!

I did try updating only the YAML component to 3.3.18, but it appeared to break something. Sadly because of how the railsphp is implemented I don't have full logging, I just basically have the web interface throwing a generic error when stuff breaks. As such I can't provide a PR. It would appear that something else in Railsphp may need more, or there may be a dependency conflict somewhere.

I really appreciate the response and hopefully it will just be something simple I overlooked on my end.

**Comment by Parziphal** [comment]
Hello again~

I updated the dependency. I had a hard time installing and testing this and my.imouto, partially because I don't really know how to properly develop a Composer package, and partially because the code is so old I got a couple errors. It's been a lot of years since I last used my.imouto.

This is the error I got when I first updated the dependency, I guess this is the error you got:

```
PHP Warning in Rails\Application\Base#_load_active_record
Invalid argument supplied for foreach() 
#0 Rails/Application/Base.php(273): Rails::errorHandler()
#1 Rails/Application/Base.php(106): Rails\Application\Base->_load_active_record()
#2 Rails/Application/Base.php(50): Rails\Application\Base->boot()
#3 config/boot.php(29): Rails\Application\Base::initialize()
#4 public/index.php(2): require('/home/blackmesa...')
#5 {main}
```

After fixing it the system worked just fine. I created a new version for the framework, `v1.0.5`.

Hopefully it works for you too. Let me know.

**Comment by nomakewan** [comment]
The error I had gotten originally was actually regarding the en.yml file for Locales when running the job task processor and curly braces. After updating the Yaml component by itself I actually didn't get any specific error in my logs, it just made the whole web app fail regardless of the job task processor.

I can confirm that after running composer update --ignore-platform-reqs with the system CLI set to PHP 7.4, your update has fixed the bug! Thank you very much, your fix has worked perfectly. As such, I'm going to go ahead and close this issue.
